### ISSUE TITLE
Doublons fichier actions_culturelles_soutenues.csv

### ISSUE THREAD

**Issue by nrouyer** [ToulouseDataViz/Hackaviz2022#1]
Concernant l'unicité des données dans le jeu de données `actions_culturelles_soutenues.csv` :
Même en prenant l'ensemble des champs, j'obtiens 52740 enregistrements uniques.
Alors que le nombre d'enregistrements dans le fichier est 53003.

**Comment by cregouby** [comment]
C'est parfaitement exact, merci @nrouyer  ! Mille excuses pour cela, je produis un correctif au plus tôt.
